### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mitani1993** [mitani1993/protospace-27537#1]
#URL
https://protospace-27537.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログイン・ログアウトの状態に関わらず、プロトタイプ詳細ページに「プロトタイプ名」が表示されるようにしましょう
 
修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mitani1993** [comment]
タイトル修正しました。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
修正箇所確認させていただきました！LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
